import { Card } from '../../cards/card.entity';

// ─── Board pieces ────────────────────────────────────────────────────────────

export type CombatMode = 'attack' | 'guard';

export interface MonsterOnBoard {
  /** Unique runtime identifier (uuid) for this specific instance on board. */
  instanceId: string;
  card: Card;
  /** Current HP after persistent damage. */
  currentHp: number;
  mode: CombatMode;
  /** Equipment supports attached to this monster. */
  equipments: Card[];
  /** Accumulated ATK buff (from terrain / equipment effects). */
  atkBuff: number;
  /** Accumulated HP buff already applied to currentHp. */
  hpBuff: number;
  /** Whether this monster has already attacked this battle phase. */
  hasAttackedThisTurn: boolean;
}

// ─── Per-player state ────────────────────────────────────────────────────────

export interface PlayerGameState {
  userId: number;
  username: string;
  socketId: string;

  /**
   * Number of remaining primes (lives).  Starts at 6.
   * The actual prime cards are stored in `primeDeck`.
   */
  primes: number;

  /**
   * The 6 cards set aside face-down at game start.
   * Removed from the top as primes are lost.
   * Stolen primes come from here and go to the thief's `hand`.
   */
  primeDeck: Card[];

  hand: Card[];
  deck: Card[];       // shuffled; face-down
  graveyard: Card[];
  banished: Card[];   // permanently removed from game

  /** 3 monster zones (null = empty). */
  monsterZones: (MonsterOnBoard | null)[];

  /** 3 support zones – permanent supports only (null = empty). */
  supportZones: (Card | null)[];

  /** Extra energy generated by recycling permanent supports this turn. */
  recycleEnergy: number;

  /** Whether the player has drawn their card this draw phase. */
  hasDrawnThisTurn: boolean;

  /** Controls the 7-card hand limit enforcement at end phase. */
  handLimitEnforced: boolean;

  /** True once the player has submitted their deck and is ready to start. */
  ready: boolean;
}

// ─── Game state ──────────────────────────────────────────────────────────────

export type GamePhase = 'waiting' | 'draw' | 'main' | 'battle' | 'end' | 'finished';

export type GameEndReason =
  | 'primes_depleted'
  | 'deck_empty'
  | 'surrender'
  | 'disconnect';

export interface GameState {
  matchId: number;
  player1: PlayerGameState;
  player2: PlayerGameState;
  /** userId of the player whose turn it currently is. */
  currentTurnUserId: number;
  phase: GamePhase;
  turnNumber: number;
  winner?: number; // userId
  endReason?: GameEndReason;
  /** Human-readable log of the last events (capped at 50 entries). */
  log: string[];
}

// ─── Client-safe views (sent over WS) ────────────────────────────────────────

/** What a player sees about their own state. */
export interface MyClientState {
  userId: number;
  username: string;
  primes: number;
  hand: Card[];
  deckCount: number;
  graveyard: Card[];
  banished: Card[];
  monsterZones: (MonsterOnBoard | null)[];
  supportZones: (Card | null)[];
  recycleEnergy: number;
}

/** What a player sees about the opponent (hidden info removed). */
export interface OpponentClientState {
  userId: number;
  username: string;
  primes: number;
  handCount: number;         // count only
  deckCount: number;
  graveyard: Card[];
  banished: Card[];
  monsterZones: (MonsterOnBoard | null)[];
  supportZones: (Card | null)[];
}

export interface ClientGameState {
  matchId: number;
  phase: GamePhase;
  turnNumber: number;
  isMyTurn: boolean;
  me: MyClientState;
  opponent: OpponentClientState;
  log: string[];
  winner?: number;
  endReason?: GameEndReason;
}
